### ISSUE TITLE
Could not find the entrypoint _pcre2_compile@40. (3260)

### ISSUE THREAD

**Issue by lievencardoen** [kiyolee/pcre2-win-build#1]
Hi, I'm trying to use the libpcre2-8.dll (built with the VS2022 solution) from an ABL Application (old 4GL Language).

I'm constantly hitting the error

`Could not find the entrypoint _pcre2_compile@40. (3260)`

I've been searching the internet for a day now and I can't seem to figure out why I'm getting this error. 

Anybody? I do see that __declspec(dllexport) is set so ...

Also had a look with dependency walker and the functions are visible.

**Comment by kiyolee** [comment]
If you check the exported entry points from `libpcre2-8.dll` (use `dumpbin` command), you can see the function name should be `pcre2_compile_8` instead of `_pcre2_compile@40`.
I have no idea how your entry point name comes by as such.

**Comment by kiyolee** [comment]
The name-decoration convention like `_foobar@12` is a consequence of using `__stdcall` calling convention.
See [here](https://learn.microsoft.com/en-us/cpp/cpp/stdcall?view=msvc-170) for more information.
The code here is compiled using default `__cdecl` calling convention and hence the simpler entry point names.

**Comment by lievencardoen** [comment]
Using pcre2_compile_8 instead of pcre2_compile does work. Thx for the anwser.
